export const schemaFiles = new Map([
  ['aegis.contract_components.v1', 'contract-components.v1.schema.json'],
  ['aegis.prepared_opinion_effect.v1', 'prepared-opinion-effect.v1.schema.json'],
  ['aegis.prepared_draft_effect.v1', 'prepared-draft-effect.v1.schema.json'],
  ['aegis.architecture_policy.v3', 'architecture-policy.v3.schema.json'],
  ['aegis.confirmation_request.v5', 'confirmation-request.v5.schema.json'],
  ['aegis.constitution.v1', 'constitution.v1.schema.json'],
  ['aegis.decision_presentation.v1', 'decision-presentation.v1.schema.json'],
  ['aegis.intent_evidence.v1', 'intent-evidence.v1.schema.json'],
  ['aegis.issue_contract.v14', 'issue-contract.v14.schema.json'],
  ['aegis.jev_assessment.v1', 'jev-assessment.v1.schema.json'],
  ['aegis.jev_comparison.v1', 'jev-comparison.v1.schema.json'],
  ['aegis.jev_decision_batch.v2', 'jev-decision-batch.v2.schema.json'],
  ['aegis.preflight_handoff.v2', 'preflight-handoff.v2.schema.json'],
  ['aegis.rejection.v1', 'rejection.v1.schema.json'],
  ['aegis.semantic_draft.v9', 'semantic-draft.v9.schema.json'],
  ['aegis.semantic_draft_decision.v1', 'semantic-draft-decision.v1.schema.json'],
  ['aegis.semantic_execution.v1', 'semantic-execution.v1.schema.json'],
  ['aegis.semantic_opinion.v3', 'semantic-opinion.v3.schema.json'],
  ['aegis.semantic_opinion_decision.v1', 'semantic-opinion-decision.v1.schema.json'],
  ['aegis.semantic_request.v10', 'semantic-request.v10.schema.json'],
  ['aegis.semantic_resolution.v2', 'semantic-resolution.v2.schema.json'],
  ['aegis.wizard_question.v1', 'wizard-question.v1.schema.json'],
  ['aegis.role_assignment.v1', 'role-assignment.v1.schema.json'],
  ['aegis.jev_advisory.v2', 'jev-advisory.v2.schema.json'],
]);

export const validatorSchemaIds = [
  'aegis.architecture_policy.v3',
  'aegis.confirmation_request.v5',
  'aegis.constitution.v1',
  'aegis.intent_evidence.v1',
  'aegis.issue_contract.v14',
  'aegis.jev_assessment.v1',
  'aegis.jev_comparison.v1',
  'aegis.jev_decision_batch.v2',
  'aegis.preflight_handoff.v2',
  'aegis.rejection.v1',
  'aegis.semantic_draft.v9',
  'aegis.semantic_execution.v1',
  'aegis.semantic_opinion.v3',
  'aegis.semantic_request.v10',
  'aegis.semantic_resolution.v2',
  'aegis.wizard_question.v1',
  'aegis.role_assignment.v1',
  'aegis.jev_advisory.v2',
];

export function validatorFileName(schemaId) {
  return `${schemaId.replaceAll('.', '_')}.cjs`;
}
