export const schemaFiles = new Map([
  ['aegis.architecture_policy.v3', 'architecture-policy.v3.schema.json'],
  ['aegis.confirmation_request.v4', 'confirmation-request.v4.schema.json'],
  ['aegis.constitution.v1', 'constitution.v1.schema.json'],
  ['aegis.issue_contract.v3', 'issue-contract.v3.schema.json'],
  ['aegis.issue_contract.v4', 'issue-contract.v4.schema.json'],
  ['aegis.issue_contract.v5', 'issue-contract.v5.schema.json'],
  ['aegis.issue_contract.v6', 'issue-contract.v6.schema.json'],
  ['aegis.issue_contract.v7', 'issue-contract.v7.schema.json'],
  ['aegis.issue_contract.v8', 'issue-contract.v8.schema.json'],
  ['aegis.issue_contract.v9', 'issue-contract.v9.schema.json'],
  ['aegis.issue_contract.v10', 'issue-contract.v10.schema.json'],
  ['aegis.issue_contract.v11', 'issue-contract.v11.schema.json'],
  ['aegis.issue_contract.v12', 'issue-contract.v12.schema.json'],
  ['aegis.issue_contract.v13', 'issue-contract.v13.schema.json'],
  ['aegis.preflight_handoff.v2', 'preflight-handoff.v2.schema.json'],
  ['aegis.rejection.v1', 'rejection.v1.schema.json'],
  ['aegis.semantic_draft.v1', 'semantic-draft.v1.schema.json'],
  ['aegis.semantic_draft.v2', 'semantic-draft.v2.schema.json'],
  ['aegis.semantic_draft.v3', 'semantic-draft.v3.schema.json'],
  ['aegis.semantic_draft.v4', 'semantic-draft.v4.schema.json'],
  ['aegis.semantic_draft.v5', 'semantic-draft.v5.schema.json'],
  ['aegis.semantic_draft.v6', 'semantic-draft.v6.schema.json'],
  ['aegis.semantic_draft.v7', 'semantic-draft.v7.schema.json'],
  ['aegis.semantic_draft.v8', 'semantic-draft.v8.schema.json'],
  ['aegis.semantic_opinion.v2', 'semantic-opinion.v2.schema.json'],
  ['aegis.semantic_request.v6', 'semantic-request.v6.schema.json'],
  ['aegis.semantic_request.v7', 'semantic-request.v7.schema.json'],
  ['aegis.semantic_request.v8', 'semantic-request.v8.schema.json'],
  ['aegis.semantic_request.v9', 'semantic-request.v9.schema.json'],
  ['aegis.semantic_worksheet.v1', 'semantic-worksheet.v1.schema.json'],
  ['aegis.semantic_resolution.v2', 'semantic-resolution.v2.schema.json'],
  ['aegis.role_assignment.v1', 'role-assignment.v1.schema.json'],
]);

export const validatorSchemaIds = [
  'aegis.architecture_policy.v3',
  'aegis.confirmation_request.v4',
  'aegis.constitution.v1',
  'aegis.issue_contract.v3',
  'aegis.issue_contract.v4',
  'aegis.issue_contract.v5',
  'aegis.issue_contract.v6',
  'aegis.issue_contract.v7',
  'aegis.issue_contract.v8',
  'aegis.issue_contract.v9',
  'aegis.issue_contract.v10',
  'aegis.issue_contract.v11',
  'aegis.issue_contract.v12',
  'aegis.issue_contract.v13',
  'aegis.preflight_handoff.v2',
  'aegis.rejection.v1',
  'aegis.semantic_draft.v8',
  'aegis.semantic_opinion.v2',
  'aegis.semantic_request.v9',
  'aegis.semantic_worksheet.v1',
  'aegis.semantic_resolution.v2',
  'aegis.role_assignment.v1',
];

export function validatorFileName(schemaId) {
  return `${schemaId.replaceAll('.', '_')}.cjs`;
}
