export const schemaFiles = new Map([
  ['aegis.contract_components.v1', 'contract-components.v1.schema.json'],
  ['aegis.prepared_opinion_effect.v1', 'prepared-opinion-effect.v1.schema.json'],
  ['aegis.prepared_draft_effect.v1', 'prepared-draft-effect.v1.schema.json'],
  ['aegis.architecture_policy.v3', 'architecture-policy.v3.schema.json'],
  ['aegis.confirmation_request.v5', 'confirmation-request.v5.schema.json'],
  ['aegis.constitution.v1', 'constitution.v1.schema.json'],
  ['aegis.decision_presentation.v1', 'decision-presentation.v1.schema.json'],
  ['aegis.intent_evidence.v1', 'intent-evidence.v1.schema.json'],
  ['aegis.issue_contract.v3', 'legacy/issue-contract.v3.schema.json'],
  ['aegis.issue_contract.v4', 'legacy/issue-contract.v4.schema.json'],
  ['aegis.issue_contract.v5', 'legacy/issue-contract.v5.schema.json'],
  ['aegis.issue_contract.v6', 'legacy/issue-contract.v6.schema.json'],
  ['aegis.issue_contract.v7', 'legacy/issue-contract.v7.schema.json'],
  ['aegis.issue_contract.v8', 'legacy/issue-contract.v8.schema.json'],
  ['aegis.issue_contract.v9', 'legacy/issue-contract.v9.schema.json'],
  ['aegis.issue_contract.v10', 'legacy/issue-contract.v10.schema.json'],
  ['aegis.issue_contract.v11', 'legacy/issue-contract.v11.schema.json'],
  ['aegis.issue_contract.v12', 'legacy/issue-contract.v12.schema.json'],
  ['aegis.issue_contract.v13', 'legacy/issue-contract.v13.schema.json'],
  ['aegis.issue_contract.v14', 'issue-contract.v14.schema.json'],
  ['aegis.jev_assessment.v1', 'jev-assessment.v1.schema.json'],
  ['aegis.jev_comparison.v1', 'jev-comparison.v1.schema.json'],
  ['aegis.jev_decision_batch.v2', 'jev-decision-batch.v2.schema.json'],
  ['aegis.preflight_handoff.v2', 'preflight-handoff.v2.schema.json'],
  ['aegis.rejection.v1', 'rejection.v1.schema.json'],
  ['aegis.semantic_draft.v1', 'legacy/semantic-draft.v1.schema.json'],
  ['aegis.semantic_draft.v2', 'legacy/semantic-draft.v2.schema.json'],
  ['aegis.semantic_draft.v3', 'legacy/semantic-draft.v3.schema.json'],
  ['aegis.semantic_draft.v4', 'legacy/semantic-draft.v4.schema.json'],
  ['aegis.semantic_draft.v5', 'legacy/semantic-draft.v5.schema.json'],
  ['aegis.semantic_draft.v6', 'legacy/semantic-draft.v6.schema.json'],
  ['aegis.semantic_draft.v7', 'legacy/semantic-draft.v7.schema.json'],
  ['aegis.semantic_draft.v8', 'legacy/semantic-draft.v8.schema.json'],
  ['aegis.semantic_draft.v9', 'semantic-draft.v9.schema.json'],
  ['aegis.semantic_draft_decision.v1', 'semantic-draft-decision.v1.schema.json'],
  ['aegis.semantic_execution.v1', 'semantic-execution.v1.schema.json'],
  ['aegis.semantic_opinion.v3', 'semantic-opinion.v3.schema.json'],
  ['aegis.semantic_opinion_decision.v1', 'semantic-opinion-decision.v1.schema.json'],
  ['aegis.semantic_request.v6', 'legacy/semantic-request.v6.schema.json'],
  ['aegis.semantic_request.v7', 'legacy/semantic-request.v7.schema.json'],
  ['aegis.semantic_request.v8', 'legacy/semantic-request.v8.schema.json'],
  ['aegis.semantic_request.v9', 'legacy/semantic-request.v9.schema.json'],
  ['aegis.semantic_request.v10', 'semantic-request.v10.schema.json'],
  ['aegis.semantic_worksheet.v1', 'semantic-worksheet.v1.schema.json'],
  ['aegis.semantic_resolution.v2', 'semantic-resolution.v2.schema.json'],
  ['aegis.wizard_question.v1', 'wizard-question.v1.schema.json'],
  ['aegis.role_assignment.v1', 'role-assignment.v1.schema.json'],
  ['aegis.jev_advisory.v2', 'jev-advisory.v2.schema.json'],
]);

export const validatorSchemaIds = [
  'aegis.architecture_policy.v3',
  'aegis.confirmation_request.v5',
  'aegis.constitution.v1',
  'aegis.intent_evidence.v1',
  'aegis.issue_contract.v3',
  'aegis.issue_contract.v4',
  'aegis.issue_contract.v5',
  'aegis.issue_contract.v6',
  'aegis.issue_contract.v7',
  'aegis.issue_contract.v8',
  'aegis.issue_contract.v9',
  'aegis.issue_contract.v10',
  'aegis.issue_contract.v11',
  'aegis.issue_contract.v12',
  'aegis.issue_contract.v13',
  'aegis.issue_contract.v14',
  'aegis.jev_assessment.v1',
  'aegis.jev_comparison.v1',
  'aegis.jev_decision_batch.v2',
  'aegis.preflight_handoff.v2',
  'aegis.rejection.v1',
  'aegis.semantic_draft.v9',
  'aegis.semantic_execution.v1',
  'aegis.semantic_opinion.v3',
  'aegis.semantic_request.v10',
  'aegis.semantic_resolution.v2',
  'aegis.wizard_question.v1',
  'aegis.role_assignment.v1',
  'aegis.jev_advisory.v2',
];

export function validatorFileName(schemaId) {
  return `${schemaId.replaceAll('.', '_')}.cjs`;
}
