#!/usr/bin/env node

import Ajv2020 from 'ajv/dist/2020.js';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import process from 'node:process';
import { fileURLToPath, URL } from 'node:url';

import {
  schemaFiles,
  validatorFileName,
  validatorSchemaIds,
} from './lib/schema_catalog.mjs';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const schemaDirectory = resolve(root, 'governance/schemas');
const outputDirectory = resolve(root, 'scripts/generated/schema_validators');
const checkOnly = process.argv.includes('--check');
const ajv = new Ajv2020({
  allErrors: true,
  strict: true,
  code: { source: true },
});

for (const file of schemaFiles.values()) {
  const document = JSON.parse(await readFile(resolve(schemaDirectory, file), 'utf8'));
  ajv.addSchema(document);
}

const expectedFiles = new Set();
const stale = [];
await mkdir(outputDirectory, { recursive: true });
for (const schemaId of validatorSchemaIds) {
  const validate = ajv.getSchema(schemaId);
  if (validate === undefined) throw new Error(`schema_unavailable:${schemaId}`);
  const file = validatorFileName(schemaId);
  expectedFiles.add(file);
  const content = `// Generated by scripts/generate_schema_validators.mjs. Do not edit.\n${standaloneCode(ajv, validate)}\n`;
  const path = resolve(outputDirectory, file);
  if (checkOnly) {
    let current = '';
    try {
      current = await readFile(path, 'utf8');
    } catch {
      // Missing output is reported uniformly below.
    }
    if (current !== content) stale.push(file);
  } else {
    await writeFile(path, content, 'utf8');
  }
}

for (const file of await readdir(outputDirectory)) {
  if (!file.endsWith('.cjs') || expectedFiles.has(file)) continue;
  if (checkOnly) stale.push(file);
  else await rm(resolve(outputDirectory, file));
}
if (stale.length > 0) {
  throw new Error(`generated_schema_validators_stale:${[...new Set(stale)].sort().join(',')}`);
}
